branch-defaults:
  dev:
    environment: udagram-singlun-development
    group_suffix: null
  ops-3-auth:
    environment: udacity-c2-restapi-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  udacity-c2-restapi-dev:
    branch: null
    repository: null
global:
  application_name: udagram-singlun-dev
  branch: null
  default_ec2_keyname: learnKey
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
